name: Deploy Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check model files
      run: |
        echo "Checking model files..."
        ls -l ./fine_tuned_roberta
        required_files=("config.json" "merges.txt" "special_tokens_map.json" "tf_model.h5" "tokenizer_config.json" "vocab.json")
        for file in "${required_files[@]}"; do
          if [ ! -f "./fine_tuned_roberta/$file" ]; then
            echo "Error: Missing $file in fine_tuned_roberta."
            exit 1
          fi
        done
        echo "All model files are present."

    - name: Start API server
      run: |
        echo "Starting API server..."
        uvicorn API:app --host 0.0.0.0 --port 5000 --log-level debug &
        echo "Waiting for API..."
        sleep 30  # Délai prolongé avant d'envoyer la requête de test
        curl -v http://127.0.0.1:5000/predict/ -d '{"text": "I love this product!"}' -H "Content-Type: application/json"
        echo "API is ready"
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.12.8/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.8/x64/lib
