name: Run API Server and Test Prediction

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git LFS
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt-get install git-lfs
        git lfs install

    - name: Download LFS files
      run: git lfs pull

    - name: Checking model files
      run: |
        echo "Checking model files..."
        ls -l ./fine_tuned_roberta
        # Afficher les fichiers du modèle pour s'assurer qu'ils sont bien téléchargés

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Assurez-vous que TensorFlow, FastAPI, transformers et autres dépendances sont installés

    - name: Start API server
      run: |
        echo "Starting API server..."
        uvicorn API:app --host 0.0.0.0 --port 5000 --log-level debug > api_logs.txt 2>&1 &
        echo "Waiting for API..."
        sleep 30  # Délai prolongé avant d'envoyer la requête de test
        curl -v http://127.0.0.1:5000/predict/ -d '{"text": "I love this product!"}' -H "Content-Type: application/json"
        echo "API is ready"

    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        pytest test_api.py --maxfail=1 --disable-warnings -q
        # Assurez-vous que vous avez un fichier de test (ex: tests/test_api.py) avec vos tests unitaires

    - name: Display API logs
      run: |
        echo "Displaying API logs:"
        cat api_logs.txt
