jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ ! -f requirements-dev.txt ]; then pip install pytest httpx tf-keras; fi

      - name: Start FastAPI server
        run: |
          nohup uvicorn API:app --host 0.0.0.0 --port 8000 &

      - name: Test API is running
        run: |
          sleep 30  # Attente pour être sûr que l'API soit lancée
          curl -X GET http://localhost:8000  # Vérifie que l'API répond

      - name: Run tests
        run: |
          export IGNORE_MLFLOW=true
          pytest
