name: Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow-cpu

      - name: Inspect model files
        run: |
          echo "Vérification des fichiers du modèle..."
          ls -lh ./fine_tuned_roberta
          for file in ./fine_tuned_roberta/*; do
            echo "Contenu de $file :"
            head -n 10 "$file"
          done

      - name: Launch API
        run: |
          nohup python API.py > api_logs.txt 2>&1 &
          echo "API lancée, en attente de sa disponibilité..."
          for i in {1..60}; do
            if curl -s http://127.0.0.1:8080; then
              echo "API disponible !"
              break
            fi
            sleep 1
          done
          if [ $i -eq 60 ]; then
            echo "L'API n'est pas disponible après 60 secondes. Échec."
            exit 1

      - name: Afficher les logs complets de l'API
        if: failure()
        run: cat api_logs.txt

      - name: Attendre 10 secondes avant les tests
        run: sleep 10

      - name: Run tests
        run: pytest test_api.py
