name: Run API Server, Test Prediction, and Deploy Docker Image to Azure

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Git LFS
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt-get install git-lfs
        git lfs install

    - name: Restore LFS Cache
      id: restore-cache
      uses: actions/cache@v3
      with:
        path: ./fine_tuned_roberta
        key: lfs-model-cache-${{ runner.os }}-models
        restore-keys: |
          lfs-model-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pytest
      run: |
        python -m pip install pytest

    - name: Start API server
      run: |
        echo "Starting API server..."
        # Démarrer l'API en arrière-plan sur le port 5000
        uvicorn API:app --host 0.0.0.0 --port 5000 --log-level debug > api_logs.txt 2>&1 &
        echo "Waiting for the API to be ready..."

        # Attendre que l'API soit prête
        while ! curl -s http://127.0.0.1:5000/docs -o /dev/null; do
          echo "API is not ready, waiting..."
          sleep 60
        done

        echo "API is ready"

    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        pytest test_api.py --maxfail=1 --disable-warnings -q

    - name: Display API logs
      run: |
        echo "Displaying API logs:"
        cat api_logs.txt

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/twit_sentiments:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/twit_sentiments:latest

    - name: Deploy Docker image to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: twisentiment-v2
        images: ${{ secrets.DOCKER_USERNAME }}/twit_sentiments:latest
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
