name: Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 autopep8 black  # Installe flake8, autopep8 et black
      - run: |
          # Formater le code avec autopep8 et black pour corriger les erreurs de style avant flake8
          autopep8 --in-place --aggressive $(find . -name "*.py")  # Formate avec autopep8
          black --line-length 79 $(find . -name "*.py")  # Formate avec black et limite à 79 caractères par ligne
      - run: |
          flake8 . || exit 1  # Exécuter flake8 après formatage et échouer si des erreurs sont détectées
      - name: Lancer l'API et vérifier sa disponibilité
        run: |
          nohup python API.py > api_logs.txt 2>&1 &  # Lance l'API en arrière-plan et redirige les logs
          echo "API lancée, en attente de sa disponibilité..."
          for i in {1..20}; do  # Essayer pendant 20 tentatives
            sleep 10  # Attendre 10 secondes entre chaque tentative
            curl -s http://127.0.0.1:5001 || echo "API non encore disponible, tentative $i"
          done
      - run: |
          pytest test_api.py  # Exécute les tests unitaires du fichier test_api.py
