name: Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          python -m venv venv
          source venv/bin/activate  # Activer l'environnement virtuel
          pip install autopep8  # Installer autopep8 si ce n'est pas dans requirements.txt
          pip install -r requirements.txt  # Réinstaller les dépendances
      - run: |
          autopep8 --in-place --aggressive $(find . -name "*.py")
          black --line-length 79 $(find . -name "*.py")
      - run: |
          flake8 . || exit 1
      - name: Lancer l'API et vérifier sa disponibilité
        run: |
          nohup python API.py > api_logs.txt 2>&1 &  # Lance l'API en arrière-plan et redirige les logs
          echo "API lancée, en attente de sa disponibilité..."
          for i in {1..20}; do
            sleep 10
            curl -s http://127.0.0.1:5001 || echo "API non encore disponible, tentative $i"
          done
      - run: |
          pytest test_api.py
