name: Run API Tests and Deploy

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests

    - name: Start MLFlow server
      run: |
        nohup mlflow server --host 0.0.0.0 --port 5001 > mlflow_logs.txt 2>&1 &
        echo "Waiting for MLFlow..."
        while ! curl -s http://127.0.0.1:5001; do 
            echo "Waiting for MLFlow to start..."
            sleep 10
        done
        echo "MLFlow is ready"
        cat mlflow_logs.txt  # Afficher les logs de MLFlow pour débogage

    - name: Start API server
      run: |
        nohup uvicorn API:app --host 0.0.0.0 --port 8080 > api_logs.txt 2>&1 &
        echo "Waiting for API..."
        while ! curl -s http://127.0.0.1:8080/predict/; do 
            echo "Waiting for API to start..."
            sleep 10
        done
        echo "API is ready"
        cat api_logs.txt  # Afficher les logs de l'API pour débogage

    - name: Run tests
      run: |
        curl -s http://127.0.0.1:8080/predict/ -X POST -d '{"text": "I love this product!"}' -H "Content-Type: application/json"
        pytest --maxfail=1 --disable-warnings -q

    # ------------- Partie Docker Hub -------------
    - name: Build Docker image
      run: |
        docker build -t my-api-image .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag my-api-image ${{ secrets.DOCKER_USERNAME }}/my-api-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-api-image:latest
