name: Run API Server and Test Prediction

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Git LFS
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        sudo apt-get install git-lfs
        git lfs install

    - name: Restore LFS Cache
      uses: actions/cache@v3
      with:
        path: ./fine_tuned_roberta
        key: lfs-model-cache-${{ github.sha }}
        restore-keys: |
          lfs-model-cache-

    - name: Check and Download LFS files
      run: |
        echo "Checking if model files exist..."
        if [ ! -f "./fine_tuned_roberta/config.json" ]; then
          echo "Model files missing. Downloading via Git LFS."
          git lfs pull
        else
          echo "Model files already present."
        fi

    - name: Save LFS Cache
      uses: actions/cache@v3
      with:
        path: ./fine_tuned_roberta
        key: lfs-model-cache-${{ github.sha }}
        restore-keys: |
          lfs-model-cache-

    - name: Checking model files
      run: |
        echo "Checking model files..."
        ls -l ./fine_tuned_roberta

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start API server
      run: |
        echo "Starting API server..."
        uvicorn API:app --host 0.0.0.0 --port 5000 --log-level debug > api_logs.txt 2>&1 &
        echo "Waiting for API to be ready..."
        for i in {1..30}; do
          curl -s http://127.0.0.1:5000/predict/ -o /dev/null && break || sleep 1
        done
        echo "API is ready"

    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        pytest test_api.py --maxfail=1 --disable-warnings -q

    - name: Display API logs
      run: |
        echo "Displaying API logs:"
        cat api_logs.txt
