name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests

    - name: Start MLFlow server
      run: |
        nohup mlflow server --host 0.0.0.0 --port 5001 > mlflow_logs.txt 2>&1 &
        echo "Waiting for MLFlow..."
        while ! curl -s http://127.0.0.1:5001; do sleep 5; done
        echo "MLFlow is ready"

    - name: Start API server
      run: |
        nohup uvicorn API:app --host 0.0.0.0 --port 8080 > api_logs.txt 2>&1 &
        echo "Waiting for API..."
        # Vérifier que l'API répond sur le bon endpoint
        while ! curl -s http://127.0.0.1:8080/predict/ > /dev/null; do sleep 5; done
        echo "API is ready"

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
