  test-api:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install pytest
      run: |
        python -m pip install pytest

    - name: Start API server
      run: |
        echo "Starting API server..."
        nohup uvicorn API:app --host 0.0.0.0 --port 5000 --log-level debug > api_logs.txt 2>&1 &
        echo "Waiting for API to be ready..."
        for i in {1..60}; do
          curl -s http://127.0.0.1:5000/predict/ -o /dev/null && break || sleep 2
        done
        echo "API is ready"

    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        pytest test_api.py --maxfail=1 --disable-warnings -q

    - name: Display API logs
      run: |
        echo "Displaying API logs:"
        cat api_logs.txt
