name: Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 autopep8 black  # Installe les dépendances nécessaires pour flake8, autopep8 et black
      - run: |
          autopep8 --in-place --aggressive .  # Formate automatiquement le code avec autopep8
      - run: |
          black .  # Formate automatiquement le code avec black
      - run: |
          flake8 . || exit 1  # Exécute flake8 et échoue si des erreurs sont détectées
      - run: |
          pytest test_api.py  # Exécute les tests unitaires du fichier test_api.py
