name: Python application

on:
  push:
    branches:
      - "main"  # Déclenche le workflow sur un push vers la branche 'main'
  pull_request:
    branches:
      - "main"  # Déclenche le workflow lors d'une demande de tirage vers la branche 'main'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ ! -f requirements-dev.txt ]; then pip install pytest httpx tf-keras; fi

      - name: Start FastAPI server
        run: |
          nohup uvicorn API:app --host 0.0.0.0 --port 8000 &  # Lance l'API FastAPI en arrière-plan

      - name: Test API is running
        run: |
          sleep 30  # Attente pour être sûr que l'API soit lancée
          curl -X GET http://localhost:8000  # Vérifie que l'API répond

      - name: Run tests
        run: |
          export IGNORE_MLFLOW=true
          pytest  # Lance les tests une fois que l'API est confirmée en fonctionnement

      - name: Archive test reports
        if: failure()
        run: |
          mkdir -p test-reports
          mv *.xml test-reports/  # Déplace les rapports de test en cas d'échec
        continue-on-error: true

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports

      - name: Upload coverage report
        if: success()
        run: |
          pip install coverage
          coverage run -m pytest
          coverage report -m
          coverage html -d coverage_html_report
        continue-on-error: true

      - name: Upload coverage artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage_html_report

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: success()

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}
