name: Python application

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow-cpu
          pip install fastapi uvicorn mlflow

      - name: Validate model files
        run: |
          echo "Vérification des fichiers nécessaires..."
          ls -lh ./fine_tuned_roberta
          required_files=("config.json" "tf_model.h5" "tokenizer_config.json" "vocab.json")
          for file in "${required_files[@]}"; do
            if [ ! -f "./fine_tuned_roberta/$file" ]; then
              echo "Erreur : fichier manquant $file"
              exit 1
            fi
          done

      - name: Launch MLFlow Server
        run: |
          nohup mlflow server --host 0.0.0.0 --port 5001 > mlflow_logs.txt 2>&1 &
          echo "MLFlow server lancé, en attente de sa disponibilité..."
          for i in {1..60}; do
            if curl -s http://127.0.0.1:5001; then
              echo "MLFlow disponible !"
              break
            fi
            sleep 1
          done
          if [ $i -eq 60 ]; then
            echo "MLFlow n'est pas disponible après 60 secondes. Échec."
            exit 1

      - name: Launch API
        run: |
          nohup uvicorn API:app --host 0.0.0.0 --port 8080 > api_logs.txt 2>&1 &
          echo "API lancée, en attente de sa disponibilité..."
          for i in {1..60}; do
            if curl -s http://127.0.0.1:8080; then
              echo "API disponible !"
              break
            fi
            sleep 1
          done
          if [ $i -eq 60 ]; then
            echo "L'API n'est pas disponible après 60 secondes. Échec."
            exit 1

      - name: Display logs if API fails
        if: failure()
        run: cat api_logs.txt

      - name: Run tests
        run: pytest test_api.py
